import "./globals.css";
import Nav from "@/components/Nav";

export const metadata = {
  title: "Web design",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="root">
        <Nav />
        {children}
        <script async src="/js/scrollUtil.js"></script>
      </body>
    </html>
  );
}
