import Footer from "@/components/Footer";
import "./globals.css";
import Nav from "@/components/Nav";

export const metadata = {
  title: "Web design",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="root">
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
